### ISSUE TITLE
Questions : How to build installer ? how do I see errors

### ISSUE THREAD

**Issue by kkum** [workspacer/workspacer#147]
Hello,

Thanks for the nice project. 
How do i Build the installer ?

**Comment by kkum** [comment]
Would it be possible to have some pre-release with the build from master ? either packaged or not.

**Comment by lauverityhill** [comment]
Link to precompiled binaries: https://workspacer.blob.core.windows.net/installers/stable/workspacer-stable-latest.msi

And link to the Workspacer website: https://www.workspacer.org/

**Comment by rickbutton** [comment]
There is a script in the `scripts` folder that will generate the installer given a complete build, but it requires tools extracted into the `tools` repo that I haven't actually checked in. The stable build on the website is automatically built using an Azure Pipeline, but I want to move this to GitHub Actions in order to make it easier to for folks to download builds.

In the mean time, if you want, you can download the "unstable" build, which is updated on every merge into master. **Warning, if you install this, you will remain on the unstable branch until you uninstall it. If I break master, you will break, no promises!**.

https://workspacer.blob.core.windows.net/installers/stable/workspacer-unstable-latest.msi

**Comment by sitiom** [comment]
Closing as it seems to be resolved already.

Also, the updated binaries have been moved to [Releases](https://github.com/workspacer/workspacer/releases) page.

> **Warning, if you install this, you will remain on the unstable branch until you uninstall it.**

As for this, you can now actually switch what branch you are on by setting the `context.Branch` on your configuration.
