### ISSUE TITLE
One Window Minimized Confusion

### ISSUE THREAD

**Issue by evanricard** [workspacer/workspacer#185]
How do I handle the pretext of minimizing one window when only one window is open in the default configuration just resize a window to a 'maximum' (with an offset from action bar)? 

I realize that window management is more geared towards handling multiple windows but I still would like a way without configuring a keybind besides windows key + down to minimize to handle the minimization of one window. 

I hope I am not being a bother..thanks.

**Comment by rickbutton** [comment]
I'm not sure I understand. Are you saying that you want to, when you have a single window open, have the ability to hide that single window?

Well, you could send the window to a workspace that isn't on a monitor, or you could swap workspaces to an empty one. You could also in theory craft a layout engine that just hides all windows as well, of course, and switch to that layout.

**Comment by evanricard** [comment]
Rick thanks sorry was on vacation. Ya that's the idea I think I should try to employ / write a hide-and-switch layout engine. Thanks!

**Comment by N1x0** [comment]
@evanricard  This should now be fixed by #197, behaviour is documented in config.md and a sensible default has been set in the configuration.template.csx file which makes sure that if only 1 window is open that this can always be minimized.

```context.CanMinimizeWindows = true; // false by default
```

Just tested it myself and it works on my machine, if you could give the newest unstable branch a spin and confirm then I'd close the issues.

**Comment by evanricard** [comment]
@N1x0 thank you for the update to the code and it appears to be working on my machine as well!

**Comment by N1x0** [comment]
glad to hear!
