### ISSUE TITLE
Anyway to make primary area of TallLayoutEngine on the Right side of the screen?

### ISSUE THREAD

**Issue by Lockszmith-GH** [workspacer/workspacer#251]
This isn't really an issue, but I couldn't find a discussion board or a forum.
(Might be a good idea to switch on GitHub's discussion feature for this repo).

**Comment by cloudhan** [comment]
I'd like to take this. Because I also have the same requirement. Simply looking into [TallLayoutEngine.cs](https://github.com/workspacer/workspacer/blob/2ac91adb96a7b7e1417e4cf66a28f89999ba771b/src/workspacer.Shared/Layout/TallLayoutEngine.cs), to layout from right to left will be quite simple though...

**Comment by dalyIsaac** [comment]
This is now part of the `unstable` release 0.9.11.56.
