### ISSUE TITLE
MS Outlook Reminder popup issue 

### ISSUE THREAD

**Issue by azinsharaf** [workspacer/workspacer#320]
Using workspacer pre-release 0.9.11.93, the MS Outlook reminder popup is being tiled in a way that can't be used. See attached.

![2022-06-09 12_12_31-Greenshot](https://user-images.githubusercontent.com/10101468/172932092-01472442-c4a2-4104-b2f2-5f2d84a8e23e.png)

**Comment by josteink** [comment]
That can probably be fixed by applying some sort of filter, like we've done for the [Windows Start-menu](https://github.com/workspacer/workspacer/issues/284) in the past.

If you can come up with a good filter, I would say Outlook is a common enough application that we should consider main-lining it into Workspacer itself :)

**Comment by azinsharaf** [comment]
Thanks @josteink . It seems adding the line below fixed the issue. The Rminder window is using the same `outlook.exe` process name. ( I checked it with ProcessExplorer tool.)

`context.WindowRouter.IgnoreProcessName("OUTLOOK.exe");`
