### ISSUE TITLE
Solution/Project Naming Convention

### ISSUE THREAD

**Issue by Zinvoke** [workspacer/workspacer#376]
I was curious as to why the root namespace is not following the typical PascalCase naming conventions was this intended or just a mistake and if so would you be open to some convention changes?

**Comment by josteink** [comment]
As for original intent, you'd have to ask the original developer @rickbutton that question :smile: 

As for now, I think changing it will mean we break lots of configs out there relying on the casing being as it is. And I don't really like making breaking changes when they're not needed.

My 2 cents.

**Comment by josteink** [comment]
If you want to clean up minor things here and there to improve the overall consistency of the code-base in non-breaking ways, I don't think you'll find any objections there. :smile:

**Comment by rickbutton** [comment]
> I'm not sure whats going on with these extras newlines maybe he fell asleep with his face on the enter button?

I care not for white space in a side project I wrote to a specific problem. White space is for the tooling to figure out, if it becomes a problem, @josteink feel free to install some kind of C# linter.

On namespaces; I didn't use `Workspacer` because the project is called `workspacer`, not `Workspacer`. I don't see any reason to change it.
